Added Keynote Speaker Announcement for Alolita Sharma
pythonindia/inpycon-blog pull request #316
Opened 2020-09-07 14:56 UTC by Sc0rpi0n101

CC: @palnabarun @sayanchowdhury

2020-09-07 15:02 UTC, sayanchowdhury requested changes

2020-09-07 15:02 UTC, sayanchowdhury commented on content/blog/2020-announcing-keynote-speaker-alolita.md
> +Summary: We are happy to announce **Alolita Sharma** as a Keynote speaker for PyCon India 2020!
```suggestion
Summary: We are happy to announce **Alolita Sharma** as a Keynote Speaker for PyCon India 2020!
```

2020-09-07 15:02 UTC, sayanchowdhury commented on content/blog/2020-announcing-keynote-speaker-alolita.md
> +We are happy to announce **Alolita Sharma** as a Keynote speaker for PyCon India 2020!
```suggestion
We are happy to announce **Alolita Sharma** as a Keynote Speaker for PyCon India 2020!
```

2020-09-08 06:34 UTC, palnabarun requested changes
Just a small nit. 2020 is repeated in the URL due to it being in the article slug as well.

2020-09-08 06:34 UTC, palnabarun commented on content/blog/2020-announcing-keynote-speaker-alolita.md
> +Slug: 2020-keynote-announcement-alolita-sharma
```suggestion
Slug: keynote-announcement-alolita-sharma
```

2020-09-08 06:37 UTC, palnabarun approved these changes

2020-09-08 10:59 UTC, sayanchowdhury approved these changes

2020-09-08 11:03 UTC, palnabarun requested changes

2020-09-08 11:03 UTC, palnabarun commented on content/blog/2020-announcing-keynote-speaker-alolita.md
> +Alolita Sharma is a Principal Technologist at Amazon Web Services. She leads open source strategy and engineering for projects focused on observability and search including OpenTelmetry, Prometheus,
```suggestion
Alolita Sharma is a Principal Technologist at Amazon Web Services. She leads open-source strategy and engineering for projects focused on observability and search including OpenTelemetry, Prometheus, Grafana, Apache Lucene, and Open Distro for Elasticsearch. Two decades of doing open source continue to inspire her. Alolita has built and led engineering teams at Wikipedia, Twitter, PayPal, and IBM. Alolita is passionate about language technologies that enable everyone to participate in the Web's information revolution. She serves on the board of [Unicode Consortium](https://www.unicode.org/consortium/consort.html) and is an invited expert on W3C and ECMA workgroups. She has served on the boards of the [Open Source Initiative (OSI)](https://opensource.org/) and [SFLC.in](https://sflc.in/). 
```

2020-09-08 11:04 UTC, palnabarun approved these changes

2020-09-08 11:04 UTC, merged