Add sponsor blog for Microsoft Azure
pythonindia/inpycon-blog pull request #333
Opened 2020-09-22 16:24 UTC by Sc0rpi0n101

CC: @vipulgupta2048 @palnabarun

2020-09-22 16:24 UTC, Sc0rpi0n101 commented on content/blog/2020-announcing-microsoft-azure-platinum-sponsor.md
> +[![Microsoft Azure](https://in.pycon.org/2020/assets/images/sponsors/<>.png)](https://azure.microsoft.com/en-in/)
Logo link to be added

2020-09-23 00:47 UTC, palnabarun requested changes

2020-09-23 00:47 UTC, palnabarun commented on content/blog/2020-announcing-microsoft-azure-platinum-sponsor.md
> +[![Microsoft Azure](https://in.pycon.org/2020/assets/images/sponsors/<>.png)](https://azure.microsoft.com/en-in/)
```suggestion
[![Microsoft Azure](https://in.pycon.org/2020/assets/images/sponsors/azure.png)](https://azure.microsoft.com/en-us/?wt.mc_id=AID3022746_QSG_474804&ocid=AID3022746_QSG_474804&WT.mc_id=pyconindia-azure-cxa)
```

2020-09-23 00:47 UTC, palnabarun commented on content/blog/2020-announcing-microsoft-azure-platinum-sponsor.md
> +Website Link: <https://azure.microsoft.com/en-in/>
```suggestion
Website Link: <https://azure.microsoft.com/en-us/?wt.mc_id=AID3022746_QSG_474804&ocid=AID3022746_QSG_474804&WT.mc_id=pyconindia-azure-cxa>
```

2020-09-23 00:49 UTC, palnabarun requested changes

2020-09-23 00:49 UTC, palnabarun commented on content/blog/2020-announcing-microsoft-azure-platinum-sponsor.md
> +Website Link: <https://azure.microsoft.com/en-in/>
```suggestion
Website Link: <https://azure.microsoft.com/en-us/?wt.mc_id=AID3022746_QSG_474804&ocid=AID3022746_QSG_474804&WT.mc_id=pyconindia-azure-cxa>
```

2020-09-23 00:53 UTC, palnabarun requested changes

2020-09-23 00:53 UTC, palnabarun commented on content/blog/2020-announcing-microsoft-azure-platinum-sponsor.md
> +Website Link: <https://azure.microsoft.com/en-us/?wt.mc_id=AID3022746_QSG_474804&ocid=AID3022746_QSG_474804&WT.mc_id=pyconindia-azure-cxa>
```suggestion
Website Link: [Microsoft Azure](https://azure.microsoft.com/en-us/?wt.mc_id=AID3022746_QSG_474804&ocid=AID3022746_QSG_474804&WT.mc_id=pyconindia-azure-cxa)
```

2020-09-23 00:54 UTC, merged