Add PyCon India 2021 Schedue Announcement blog
pythonindia/inpycon-blog pull request #384
Opened 2021-08-01 12:46 UTC by vipulgupta2048

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

* **Please check if the PR fulfills these requirements**

- [ ] Screenshots for changes (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-08-01 14:42 UTC, raukadah requested changes
Looks good few wdits

2021-08-01 14:42 UTC, raukadah commented on content/blog/2021/2021-announce-final-schedule.md
> +Date: 2020-08-02 17:00
2021

2021-08-01 14:42 UTC, raukadah commented on content/blog/2021/2021-announce-final-schedule.md
> +
28 talks and 6 workshop

2021-08-01 14:42 UTC, raukadah commented on content/blog/2021/2021-announce-final-schedule.md
> +**Checkout the [PyCon India 2021 schedule](https://in.pycon.org/2021/schedule/)**
https://in.pycon.org/2021/#schedule

2021-08-01 18:59 UTC, vipulgupta2048 commented on content/blog/2021/2021-announce-final-schedule.md
> +**Checkout the [PyCon India 2021 schedule](https://in.pycon.org/2021/schedule/)**
Right on.

2021-08-01 19:08 UTC, vipulgupta2048 commented
Closes https://github.com/pythonindia/inpycon2021-tasks/issues/83

2021-08-02 02:56 UTC, raukadah approved these changes

2021-08-02 02:56 UTC, raukadah commented
@anistark @RiteshAgrawal

2021-08-02 11:27 UTC, anistark approved these changes

2021-08-02 11:28 UTC, merged