Fix the Inkind sponsors announcement blog's title
pythonindia/inpycon-blog pull request #393
Opened 2021-09-07 08:54 UTC by Sc0rpi0n101

CC: @raukadah @anistark @vipulgupta2048

2021-09-07 09:16 UTC, chkumar246 approved these changes

2021-09-07 09:17 UTC, chkumar246 commented
2:24:33 PM: Collecting unidecode
2:24:33 PM:   Downloading Unidecode-1.3.0-py2.py3-none-any.whl (235 kB)
2:24:33 PM: ERROR: Package 'unidecode' requires a different Python: 2.7.12 not in '>=3.5'
2:24:34 PM: Error installing pip dependencies

2021-09-09 22:26 UTC, realslimshanky requested changes
@Sc0rpi0n101 Please rebase your branch with master in order to resolve Netlify build error.

2021-09-10 05:11 UTC, raukadah commented
@Sc0rpi0n101 I have updated the deepsource description, It was requested by them.

2021-09-10 05:11 UTC, raukadah approved these changes

2021-09-10 17:12 UTC, vipulgupta2048 approved these changes

2021-09-10 17:12 UTC, merged