Add Fireducks announcement blog
pythonindia/inpycon-blog pull request #465
Opened 2024-08-31 12:35 UTC by Sc0rpi0n101

2024-09-01 16:19 UTC, harisibrahimkv requested changes

2024-09-01 16:19 UTC, harisibrahimkv commented on content/blog/2024/announcing-fireducks-as-silver-sponsor.md
> +We are immensely grateful to E2E Networks for their generous support.
Change `E2E` to `Fireducks`.

2024-09-02 07:24 UTC, Sc0rpi0n101 commented on content/blog/2024/announcing-fireducks-as-silver-sponsor.md
> +We are immensely grateful to E2E Networks for their generous support.
```suggestion
We are immensely grateful to Fireducks for their generous support.
```

2024-09-02 07:35 UTC, harisibrahimkv approved these changes

2024-09-02 08:58 UTC, merged